# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/download_video.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(564, 321)
        self.console = QtWidgets.QPlainTextEdit(Form)
        self.console.setGeometry(QtCore.QRect(20, 10, 521, 191))
        self.console.setObjectName("console")
        self.url_video = QtWidgets.QLineEdit(Form)
        self.url_video.setGeometry(QtCore.QRect(20, 220, 521, 21))
        self.url_video.setStyleSheet("")
        self.url_video.setText("")
        self.url_video.setObjectName("url_video")
        self.download = QtWidgets.QPushButton(Form)
        self.download.setGeometry(QtCore.QRect(20, 250, 521, 31))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        self.download.setFont(font)
        self.download.setObjectName("download")
        self.video_path = QtWidgets.QPushButton(Form)
        self.video_path.setGeometry(QtCore.QRect(20, 280, 521, 31))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        self.video_path.setFont(font)
        self.video_path.setObjectName("video_path")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.download.setText(_translate("Form", "Скачать видео"))
        self.video_path.setText(_translate("Form", "Папка для сохранения видео"))
